package com.friday.cultivation.network;

import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.network.NetworkRegistry;
import net.minecraftforge.network.simple.SimpleChannel;

/**
 * 网络通道注册
 */
public class ModNetwork {

    private static final String PROTOCOL_VERSION = "1";
    public static final SimpleChannel CHANNEL = NetworkRegistry.newSimpleChannel(
            new ResourceLocation("friday_cultivation", "main"),
            () -> PROTOCOL_VERSION,
            PROTOCOL_VERSION::equals,
            PROTOCOL_VERSION::equals
    );

    private static int packetId = 0;

    public static void register() {
        CHANNEL.registerMessage(
                packetId++,
                SetMeditatingPacket.class,
                SetMeditatingPacket::encode,
                SetMeditatingPacket::decode,
                SetMeditatingPacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                SpendZhenyuanPacket.class,
                SpendZhenyuanPacket::encode,
                SpendZhenyuanPacket::decode,
                SpendZhenyuanPacket::handle
        );
        // ── 身份抽取网络包 (Phase 8) ──
        CHANNEL.registerMessage(
                packetId++,
                OpenIdentityDrawPacket.class,
                OpenIdentityDrawPacket::encode,
                OpenIdentityDrawPacket::decode,
                OpenIdentityDrawPacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                ConfirmIdentityDrawPacket.class,
                ConfirmIdentityDrawPacket::encode,
                ConfirmIdentityDrawPacket::decode,
                ConfirmIdentityDrawPacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                ChooseOriginPacket.class,
                ChooseOriginPacket::encode,
                ChooseOriginPacket::decode,
                ChooseOriginPacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                OriginRandomizedPacket.class,
                OriginRandomizedPacket::encode,
                OriginRandomizedPacket::decode,
                OriginRandomizedPacket::handle
        );
        // ── 法术施放网络包 (Phase 9) ──
        CHANNEL.registerMessage(
                packetId++,
                CastSpellPacket.class,
                CastSpellPacket::encode,
                CastSpellPacket::decode,
                CastSpellPacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                SelectSpellSlotPacket.class,
                SelectSpellSlotPacket::encode,
                SelectSpellSlotPacket::decode,
                SelectSpellSlotPacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                EquipSpellPacket.class,
                EquipSpellPacket::encode,
                EquipSpellPacket::decode,
                EquipSpellPacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                EquipTechniquePacket.class,
                EquipTechniquePacket::encode,
                EquipTechniquePacket::decode,
                EquipTechniquePacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                ExecuteRefiningPacket.class,
                ExecuteRefiningPacket::encode,
                ExecuteRefiningPacket::decode,
                ExecuteRefiningPacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                ToggleSpellPacket.class,
                ToggleSpellPacket::encode,
                ToggleSpellPacket::decode,
                ToggleSpellPacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                ToggleBonusCategoryPacket.class,
                ToggleBonusCategoryPacket::encode,
                ToggleBonusCategoryPacket::decode,
                ToggleBonusCategoryPacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                SetCultivationNamePacket.class,
                SetCultivationNamePacket::encode,
                SetCultivationNamePacket::decode,
                SetCultivationNamePacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                CycleGenderPacket.class,
                CycleGenderPacket::encode,
                CycleGenderPacket::decode,
                CycleGenderPacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                SetSpellTerrainDestructionPacket.class,
                SetSpellTerrainDestructionPacket::encode,
                SetSpellTerrainDestructionPacket::decode,
                SetSpellTerrainDestructionPacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                RequestGoDifuPacket.class,
                RequestGoDifuPacket::encode,
                RequestGoDifuPacket::decode,
                RequestGoDifuPacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                SetTimeAccelerationPacket.class,
                SetTimeAccelerationPacket::encode,
                SetTimeAccelerationPacket::decode,
                SetTimeAccelerationPacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                RequestReincarnationScreenPacket.class,
                RequestReincarnationScreenPacket::encode,
                RequestReincarnationScreenPacket::decode,
                RequestReincarnationScreenPacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                OpenDeathChoicePacket.class,
                OpenDeathChoicePacket::encode,
                OpenDeathChoicePacket::decode,
                OpenDeathChoicePacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                DeathChoicePacket.class,
                DeathChoicePacket::encode,
                DeathChoicePacket::decode,
                DeathChoicePacket::handle
        );
        // ── 地府转世网络包 (Phase 15) ──
        CHANNEL.registerMessage(
                packetId++,
                OpenReincarnationPacket.class,
                OpenReincarnationPacket::encode,
                OpenReincarnationPacket::decode,
                OpenReincarnationPacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                ReincarnationChoicePacket.class,
                ReincarnationChoicePacket::encode,
                ReincarnationChoicePacket::decode,
                ReincarnationChoicePacket::handle
        );
        // ── 地府完整版网络包 ──
        CHANNEL.registerMessage(
                packetId++,
                SoulHookVisualPacket.class,
                SoulHookVisualPacket::encode,
                SoulHookVisualPacket::decode,
                SoulHookVisualPacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                SoulHookProgressPacket.class,
                SoulHookProgressPacket::encode,
                SoulHookProgressPacket::decode,
                SoulHookProgressPacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                SoulReaperTeleportPacket.class,
                SoulReaperTeleportPacket::encode,
                SoulReaperTeleportPacket::decode,
                SoulReaperTeleportPacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                SoulStatePacket.class,
                SoulStatePacket::encode,
                SoulStatePacket::decode,
                SoulStatePacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                DeathSequencePacket.class,
                DeathSequencePacket::encode,
                DeathSequencePacket::decode,
                DeathSequencePacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                SyncImmortalDarkVisionPacket.class,
                SyncImmortalDarkVisionPacket::encode,
                SyncImmortalDarkVisionPacket::decode,
                SyncImmortalDarkVisionPacket::handle
        );
        // ── 炼丹网络包 (Phase 17) ──
        CHANNEL.registerMessage(
                packetId++,
                AutoFillRecipePacket.class,
                AutoFillRecipePacket::encode,
                AutoFillRecipePacket::decode,
                AutoFillRecipePacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                ExecuteAlchemyPacket.class,
                ExecuteAlchemyPacket::encode,
                ExecuteAlchemyPacket::decode,
                ExecuteAlchemyPacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                ToggleAlchemyGhostPacket.class,
                ToggleAlchemyGhostPacket::encode,
                ToggleAlchemyGhostPacket::decode,
                ToggleAlchemyGhostPacket::handle
        );
        // ── 炼器网络包 (Phase 13 续) ──
        CHANNEL.registerMessage(
                packetId++,
                AutoFillRefiningRecipePacket.class,
                AutoFillRefiningRecipePacket::encode,
                AutoFillRefiningRecipePacket::decode,
                AutoFillRefiningRecipePacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                SetRefiningAutoRetryPacket.class,
                SetRefiningAutoRetryPacket::encode,
                SetRefiningAutoRetryPacket::decode,
                SetRefiningAutoRetryPacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                ToggleRefiningGhostPacket.class,
                ToggleRefiningGhostPacket::encode,
                ToggleRefiningGhostPacket::decode,
                ToggleRefiningGhostPacket::handle
        );
        // ── 命元天平视觉同步包 (Phase 18) ──
        CHANNEL.registerMessage(
                packetId++,
                LifeBalanceVisualPacket.class,
                LifeBalanceVisualPacket::encode,
                LifeBalanceVisualPacket::decode,
                LifeBalanceVisualPacket::handle
        );
        // ── 灵气护盾受击同步包 (Phase 18) ──
        CHANNEL.registerMessage(
                packetId++,
                QiShieldHitPacket.class,
                QiShieldHitPacket::encode,
                QiShieldHitPacket::decode,
                QiShieldHitPacket::handle
        );
        // ── 境界压制视觉同步包 (Phase 18) ──
        CHANNEL.registerMessage(
                packetId++,
                RealmPressureVisualPacket.class,
                RealmPressureVisualPacket::encode,
                RealmPressureVisualPacket::decode,
                RealmPressureVisualPacket::handle
        );
        // ── 佛怒火莲爆发同步包 (Phase 18) ──
        CHANNEL.registerMessage(
                packetId++,
                BuddhaFireLotusFlashPacket.class,
                BuddhaFireLotusFlashPacket::encode,
                BuddhaFireLotusFlashPacket::decode,
                BuddhaFireLotusFlashPacket::handle
        );
        // ── 掌雷视觉同步包 (Phase 18) ──
        CHANNEL.registerMessage(
                packetId++,
                PalmThunderVisualPacket.class,
                PalmThunderVisualPacket::encode,
                PalmThunderVisualPacket::decode,
                PalmThunderVisualPacket::handle
        );
        // ── 凌空跃步触发包 (Phase 18, 客户端→服务端) ──
        CHANNEL.registerMessage(
                packetId++,
                AirJumpPacket.class,
                AirJumpPacket::encode,
                AirJumpPacket::decode,
                AirJumpPacket::handle
        );
        // ── 灵气被吸收反馈包 (Phase 18) ──
        CHANNEL.registerMessage(
                packetId++,
                QiAbsorbedPacket.class,
                QiAbsorbedPacket::encode,
                QiAbsorbedPacket::decode,
                QiAbsorbedPacket::handle
        );
        // ── 影遁步触发包 (Phase 18, 客户端→服务端) ──
        CHANNEL.registerMessage(
                packetId++,
                ShadowStepPacket.class,
                ShadowStepPacket::encode,
                ShadowStepPacket::decode,
                ShadowStepPacket::handle
        );
        // ── 勾魂目标列表同步包 (Phase 14, 服务端→客户端) ──
        CHANNEL.registerMessage(
                packetId++,
                SoulReaperTargetsPacket.class,
                SoulReaperTargetsPacket::encode,
                SoulReaperTargetsPacket::decode,
                SoulReaperTargetsPacket::handle
        );
        // ── 修仙数据完整同步包 (Phase 18, 服务端→客户端) ──
        CHANNEL.registerMessage(
                packetId++,
                SyncCultivationDataPacket.class,
                SyncCultivationDataPacket::encode,
                SyncCultivationDataPacket::decode,
                SyncCultivationDataPacket::handle
        );
        // ── 时间凝滞·领域同步包 (Phase 18, 服务端→客户端) ──
        CHANNEL.registerMessage(
                packetId++,
                TimeStasisDomainPacket.class,
                TimeStasisDomainPacket::encode,
                TimeStasisDomainPacket::decode,
                TimeStasisDomainPacket::handle
        );
        // ── 时间凝滞·单体目标同步包 (Phase 18, 服务端→客户端) ──
        CHANNEL.registerMessage(
                packetId++,
                TimeStasisTargetPacket.class,
                TimeStasisTargetPacket::encode,
                TimeStasisTargetPacket::decode,
                TimeStasisTargetPacket::handle
        );
        // ── 法相显现包 (R42, 服务端→客户端) ──
        CHANNEL.registerMessage(
                packetId++,
                DharmaBodyManifestationPacket.class,
                DharmaBodyManifestationPacket::encode,
                DharmaBodyManifestationPacket::decode,
                DharmaBodyManifestationPacket::handle
        );
        // ── 劫云包 (R43, 服务端→客户端) ──
        CHANNEL.registerMessage(
                packetId++,
                TribulationCloudPacket.class,
                TribulationCloudPacket::encode,
                TribulationCloudPacket::decode,
                TribulationCloudPacket::handle
        );
        // ── 虚空遁·入场特效包 (R44, 服务端→客户端) ──
        CHANNEL.registerMessage(
                packetId++,
                VoidEscapeEntryEffectPacket.class,
                VoidEscapeEntryEffectPacket::encode,
                VoidEscapeEntryEffectPacket::decode,
                VoidEscapeEntryEffectPacket::handle
        );
        // ── 神识扫描包 (R45, 服务端→客户端) ──
        CHANNEL.registerMessage(
                packetId++,
                DivineSenseScanPacket.class,
                DivineSenseScanPacket::encode,
                DivineSenseScanPacket::decode,
                DivineSenseScanPacket::handle
        );
        // ── 虚空步包 (R46, 客户端→服务端) ──
        CHANNEL.registerMessage(
                packetId++,
                VoidStepPacket.class,
                VoidStepPacket::encode,
                VoidStepPacket::decode,
                VoidStepPacket::handle
        );
        // ── 选择法术槽包 (R49, 客户端→服务端) ──
        CHANNEL.registerMessage(
                packetId++,
                SelectSpellSlotPacket.class,
                SelectSpellSlotPacket::encode,
                SelectSpellSlotPacket::decode,
                SelectSpellSlotPacket::handle
        );
        // ── 装备功法包 (R50, 客户端→服务端) ──
        CHANNEL.registerMessage(
                packetId++,
                EquipTechniquePacket.class,
                EquipTechniquePacket::encode,
                EquipTechniquePacket::decode,
                EquipTechniquePacket::handle
        );
        // ── 装备法术包 (R51, 客户端→服务端) ──
        CHANNEL.registerMessage(
                packetId++,
                EquipSpellPacket.class,
                EquipSpellPacket::encode,
                EquipSpellPacket::decode,
                EquipSpellPacket::handle
        );
        // ── 结束蓄力法术包 (R52, 客户端→服务端) ──
        CHANNEL.registerMessage(
                packetId++,
                EndChargeSpellPacket.class,
                EndChargeSpellPacket::encode,
                EndChargeSpellPacket::decode,
                EndChargeSpellPacket::handle
        );
        // ── 打开死亡选择包 (R53, 服务端→客户端) ──
        CHANNEL.registerMessage(
                packetId++,
                OpenDeathChoicePacket.class,
                OpenDeathChoicePacket::encode,
                OpenDeathChoicePacket::decode,
                OpenDeathChoicePacket::handle
        );
        // ── 灵体防御开关包 (R54, 客户端→服务端) ──
        CHANNEL.registerMessage(
                packetId++,
                ToggleBodyDefensePacket.class,
                ToggleBodyDefensePacket::encode,
                ToggleBodyDefensePacket::decode,
                ToggleBodyDefensePacket::handle
        );
        // ── 编辑玩家属性包 (R55, 客户端→服务端) ──
        CHANNEL.registerMessage(
                packetId++,
                EditPlayerStatsPacket.class,
                EditPlayerStatsPacket::encode,
                EditPlayerStatsPacket::decode,
                EditPlayerStatsPacket::handle
        );
        // ── 宗门友伤开关包 (R56, 客户端→服务端) ──
        CHANNEL.registerMessage(
                packetId++,
                SetSectFriendlyFirePacket.class,
                SetSectFriendlyFirePacket::encode,
                SetSectFriendlyFirePacket::decode,
                SetSectFriendlyFirePacket::handle
        );
        // ── 释放剑气包 (R57, 客户端→服务端) ──
        CHANNEL.registerMessage(
                packetId++,
                FireSwordAuraPacket.class,
                FireSwordAuraPacket::encode,
                FireSwordAuraPacket::decode,
                FireSwordAuraPacket::handle
        );
        // ── 客户端仅高亮包 (R58, 服务端→客户端) ──
        CHANNEL.registerMessage(
                packetId++,
                ClientOnlyGlowPacket.class,
                ClientOnlyGlowPacket::encode,
                ClientOnlyGlowPacket::decode,
                ClientOnlyGlowPacket::handle
        );
        // ── 阵法控制台网络包 (Phase 阵法) ──
        CHANNEL.registerMessage(
                packetId++,
                SetFormationNamePacket.class,
                SetFormationNamePacket::encode,
                SetFormationNamePacket::decode,
                SetFormationNamePacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                SetFormationFlagPreviewPacket.class,
                SetFormationFlagPreviewPacket::encode,
                SetFormationFlagPreviewPacket::decode,
                SetFormationFlagPreviewPacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                SetFormationFlagRadiusPacket.class,
                SetFormationFlagRadiusPacket::encode,
                SetFormationFlagRadiusPacket::decode,
                SetFormationFlagRadiusPacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                ToggleFormationPacket.class,
                ToggleFormationPacket::encode,
                ToggleFormationPacket::decode,
                ToggleFormationPacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                SyncFormationFlagsPacket.class,
                SyncFormationFlagsPacket::encode,
                SyncFormationFlagsPacket::decode,
                SyncFormationFlagsPacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                SyncFormationPreviewPacket.class,
                SyncFormationPreviewPacket::encode,
                SyncFormationPreviewPacket::decode,
                SyncFormationPreviewPacket::handle
        );
        // ── 宗门系统/突破/散修交易网络包 ──
        CHANNEL.registerMessage(
                packetId++,
                SectTaskActionPacket.class,
                SectTaskActionPacket::encode,
                SectTaskActionPacket::decode,
                SectTaskActionPacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                RequestSectJoinDialoguePacket.class,
                RequestSectJoinDialoguePacket::encode,
                RequestSectJoinDialoguePacket::decode,
                RequestSectJoinDialoguePacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                RequestBreakthroughPacket.class,
                RequestBreakthroughPacket::encode,
                RequestBreakthroughPacket::decode,
                RequestBreakthroughPacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                OpenSectJoinDialoguePacket.class,
                OpenSectJoinDialoguePacket::encode,
                OpenSectJoinDialoguePacket::decode,
                OpenSectJoinDialoguePacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                JoinSectPacket.class,
                JoinSectPacket::encode,
                JoinSectPacket::decode,
                JoinSectPacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                ExecuteSundryTradePacket.class,
                ExecuteSundryTradePacket::encode,
                ExecuteSundryTradePacket::decode,
                ExecuteSundryTradePacket::handle
        );
        CHANNEL.registerMessage(
                packetId++,
                ExecuteCultivatorTradePacket.class,
                ExecuteCultivatorTradePacket::encode,
                ExecuteCultivatorTradePacket::decode,
                ExecuteCultivatorTradePacket::handle
        );
    }
}
